language: c
compiler: gcc
sudo: false
addons:
  apt:
  sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - libedit-dev
install:
- sudo apt-get install libedit-dev
script:
- make all
